2.1
KhetagKasumov/TKI-141-Prigraming pull request #4
Opened 2022-11-03 13:03 UTC by KhetagKasumov

2022-11-03 14:57 UTC, MarinaPaley requested changes

2022-11-03 14:57 UTC, MarinaPaley commented on 2.1.cpp
> +    return pow(((x2 - x1) * (x2 - x1)) + ((y2 - y1) * (y2 - y1)), 0.5) + pow(((x3 - x2) * (x3 - x2)) + ((y3 - y2) * (y3 - y2)), 0.5) + pow(((x1 - x3) * (x1 - x3)) + ((y1 - y3) * (y1 - y3)), 0.5);
не нужно использовать `pow(..., 0.5)`, использовать `std::sqrt(..., 0.5)`

2022-11-03 14:57 UTC, MarinaPaley commented on 2.1.cpp
> +        const auto Area = getArea(x1, y1, x2, y2, x3, y3, half);
[**Nit**](https://google.github.io/eng-practices/review/reviewer/standard.html): [локальные переменные именуются с маленькой (строчной) буквы](https://google.github.io/styleguide/cppguide.html#Variable_Names).

2022-11-10 13:05 UTC, KhetagKasumov commented
![image](https://user-images.githubusercontent.com/113605412/201099062-637a2493-acc5-4b76-bc7f-2b2692f136fa.png)
http://www.treugolniki.ru/ploshhad-treugolnika-po-koordinatam-vershin/

2022-11-10 13:06 UTC, KhetagKasumov commented
![image](https://user-images.githubusercontent.com/113605412/201099397-ca0c7bdb-1141-4595-ad41-88f71d7b9874.png)
https://uchi.ru/otvety/questions/naydite-perimetr-treugolnika-qpr-esli-izvestni-koordinati-ego-vershin-q-5-3-p-2-1-r-2-0

2022-11-10 14:06 UTC, MarinaPaley approved these changes

2022-12-29 03:03 UTC, merged